# Nome do workflow
name: Primeiro CI de teste

# Declara eventos que disparam o workflow
on:
    push:
        branches:
            - dev

# Declara o que será executado
jobs:
    log_test:
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout"
              uses: actions/checkout@v4

            - name: "Log básico"
              run: echo "Disparado com sucesso!"

            - name: "Log de Contexto"
              run: |
                  echo "Repositorio: ${{ github.repository }}"
                  echo "Branch: ${{ github.ref_name }}"
                  echo "Autor: ${{ github.actor }}"
                  echo "Commit: ${{ github.sha }}"

            - name: "Exibindo diretórios"
              run: ls -la

            - name: "Conteudo de .github/workflows"
              run: |
                  cd .github/workflows
                  ls -la

            - name: "Encerramento"
              run: |
                  echo "Pipeline executado com sucesso!"
                  echo "Encerrando..."
